DROP TABLE "DEMO_STAGIAIRE";
--------------------------------------------------------
--  DDL for Table DEMO_STAGIAIRE
--------------------------------------------------------

  CREATE TABLE "DEMO_STAGIAIRE" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                ,"IDENTIFICATION_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"NOM" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"PRENOM" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"DATE_NAISSANCE" DATE
                                ,"NO_TEL" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"ADRESSE_COURRIEL" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"CREE_LE" DATE
                                ,"CREE_PAR" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"MODIFIE_LE" DATE
                                ,"MODIFIE_PAR" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "DEMO_STAGIAIRE"."APP_ID" IS 'Application ID to relate to the specificity';
   COMMENT ON COLUMN "DEMO_STAGIAIRE"."PAGE_ID" IS 'Page ID to relate to the specificity';
   
--------------------------------------------------------
--  DDL for Index ID_SPC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_SPC_PK" ON "DEMO_STAGIAIRE" ("ID");
--------------------------------------------------------
--  DDL for Index DEMO_STAGIAIRE_UK1
--------------------------------------------------------

  --CREATE UNIQUE INDEX "DEMO_STAGIAIRE_UK1" ON "DEMO_STAGIAIRE" ("APP_ID", "PAGE_ID", "SPC_CODE");
--------------------------------------------------------
--  DDL for Index DEMO_STAGIAIRE_IDX1
--------------------------------------------------------

  --CREATE INDEX "DEMO_STAGIAIRE_IDX1" ON "DEMO_STAGIAIRE" ("ID", "APP_ID", "PAGE_ID"/*, "SPC_CODE"*/);
--------------------------------------------------------
--  DDL for Trigger DEMO_STAGIAIRE_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_STAGIAIRE_BIU" 
    before insert or update  
    on DEMO_STAGIAIRE 
    for each row
begin
    if inserting and :new.created is null then
        select nvl(max(d.disp_seq) + 10, 10)
        into :new.disp_seq
        from DEMO_STAGIAIRE d
        where d.app_id = :new.app_id
        and   d.page_id = :new.page_id
        and   d.group_def_id = :new.group_def_id;

        :new.spc_code   := 'ITEM_' || :new.id;
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    if updating and :new.group_def_id != :old.group_def_id then
        select nvl(max(d.disp_seq) + 10, 10)
        into :new.disp_seq
        from DEMO_STAGIAIRE d
        where d.app_id = :new.app_id
        and   d.page_id = :new.page_id
        and   d.group_def_id = :new.group_def_id;
    end if;
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end DEMO_STAGIAIRE_BIU;
--------------------------------------------------------
--  Constraints for Table DEMO_STAGIAIRE
--------------------------------------------------------

  --ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("APP_ID" NOT NULL ENABLE); 
  --ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("PAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("SPC_CODE" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("DISP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("FIELD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);

  ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "ID_SPC_PK" PRIMARY KEY ("ID") USING INDEX "ID_SPC_PK"  ENABLE;
  ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_UK1" UNIQUE ("APP_ID", "PAGE_ID", "SPC_CODE") USING INDEX  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table DEMO_STAGIAIRE
--------------------------------------------------------
  
  ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_FK1" FOREIGN KEY ("GROUP_DEF_ID") REFERENCES "SPC_GROUP_DEFINITION" ("ID") ENABLE;
  ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_FK2" FOREIGN KEY ("FORMAT_ID") REFERENCES "SPC_FORMAT" ("ID") ENABLE;
  --ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_FK1" FOREIGN KEY ("SPC_CONDITION_PRNT_ID") REFERENCES "DEMO_STAGIAIRE" ("ID") ENABLE; --?
  --ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_FK2" FOREIGN KEY ("SPC_CONDITION_DISP_ID") REFERENCES "DEMO_STAGIAIRE" ("ID") ENABLE; --?
  --ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "DEMO_STAGIAIRE_FK3" FOREIGN KEY ("COUNTER_CODE") REFERENCES "SPC_VAL_COUNTER" ("CODE") ENABLE;