DROP TABLE "DEMO_STAGIAIRE";
--------------------------------------------------------
--  DDL for Table DEMO_STAGIAIRE
--------------------------------------------------------

  CREATE TABLE "DEMO_STAGIAIRE" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                ,"IDENTIFICATION_NO" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"NOM" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"PRENOM" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"DATE_NAISSANCE" DATE
                                ,"NO_TEL" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"ADRESSE_COURRIEL" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                ,"CREE_LE" DATE
                                ,"CREE_PAR" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                ,"MODIFIE_LE" DATE
                                ,"MODIFIE_PAR" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                )  DEFAULT COLLATION "USING_NLS_COMP";
   
--------------------------------------------------------
--  DDL for Index ID_STAGIAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_STAGIAIRE_PK" ON "DEMO_STAGIAIRE" ("ID");
--------------------------------------------------------
--  DDL for Trigger DEMO_STAGIAIRE_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO_STAGIAIRE_BIU" 
    before insert or update  
    on DEMO_STAGIAIRE 
    for each row
begin
    if inserting and :new.cree_le is null then
        :new.cree_le    := sysdate; 
        :new.cree_par   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modifie_le    := sysdate; 
    :new.modifie_par   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end DEMO_STAGIAIRE_BIU;
/
ALTER TRIGGER "DEMO_STAGIAIRE_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMO_STAGIAIRE
--------------------------------------------------------

  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("IDENTIFICATION_NO" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("DATE_NAISSANCE" NOT NULL ENABLE);

  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("CREE_LE" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("CREE_PAR" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("MODIFIE_LE" NOT NULL ENABLE);
  ALTER TABLE "DEMO_STAGIAIRE" MODIFY ("MODIFIE_PAR" NOT NULL ENABLE);

  ALTER TABLE "DEMO_STAGIAIRE" ADD CONSTRAINT "ID_STAGIAIRE_PK" PRIMARY KEY ("ID") USING INDEX "ID_STAGIAIRE_PK"  ENABLE;
  