DROP TABLE "FLW_NOTIFICATION_LANG";
--------------------------------------------------------
--  DDL for Table FLW_NOTIFICATION_LANG
--------------------------------------------------------

  CREATE TABLE "FLW_NOTIFICATION_LANG" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                       , "NOTIF_ID" NUMBER
                                       , "LANG_ID" NUMBER
                                       , "SUBJECT" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                       --, "NOTIF_TEMPLATE" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                                       , "DETAIL" CLOB COLLATE "USING_NLS_COMP"
                                       , "CREATED" DATE
                                       , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                       , "MODIFIED" DATE
                                       , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                       )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."ID" IS 'Unique identifier';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."NOTIF_ID" IS 'Notification ID';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."LANG_ID" IS 'Language ID';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."SUBJECT" IS 'Subject of the notification';
   --COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."NOTIF_TEMPLATE" IS 'Notification template';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."DETAIL" IS 'Detail of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."CREATED" IS 'Creation date of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."CREATED_BY" IS 'Creator of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."MODIFIED" IS 'Modification date of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION_LANG"."MODIFIED_BY" IS 'Modifier of the notification';
--------------------------------------------------------
--  DDL for Index FLW_NOTIFICATION_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLW_NOTIFICATION_LANG_PK" ON "FLW_NOTIFICATION_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index FLW_NOTIFICATION_LANG_UN1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLW_NOTIFICATION_LANG_UN1" ON "FLW_NOTIFICATION_LANG" ("NOTIF_ID", "LANG_ID");
--------------------------------------------------------
--  DDL for Trigger FLW_NOTIFICATION_LANG_BIU_TRG
--------------------------------------------------------

 CREATE OR REPLACE EDITIONABLE TRIGGER "FLW_NOTIFICATION_LANG_BIU" 
    before insert or update  
    on FLW_NOTIFICATION_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end FLW_NOTIFICATION_LANG_BIU;
 /
ALTER TRIGGER "FLW_NOTIFICATION_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table FLW_NOTIFICATION_LANG
--------------------------------------------------------
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("NOTIF_ID" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("SUBJECT" NOT NULL ENABLE);
  --ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("NOTIF_TEMPLATE" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("DETAIL" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION_LANG" ADD CONSTRAINT "FLW_NOTIFICATION_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "FLW_NOTIFICATION_LANG" ADD CONSTRAINT "FLW_NOTIFICATION_LANG_UN1" UNIQUE ("NOTIF_ID","LANG_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------

  ALTER TABLE "FLW_NOTIFICATION_LANG" ADD CONSTRAINT "FLW_NOTIFICATION_LANG_FK1" FOREIGN KEY ("NOTIF_ID") REFERENCES "FLW_NOTIFICATION" ("ID") ENABLE;

