--DROP TABLE "FLW_STEP_ACTION_SPC_SYNC";
--------------------------------------------------------
--  DDL for Table FLW_STEP_ACTION_SPC_SYNC
--------------------------------------------------------

  CREATE TABLE "FLW_STEP_ACTION_SPC_SYNC" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                          --, "SOURCE_TYPE_FLOW_ID" NUMBER
                                          --, "TARGET_TYPE_FLOW_ID" NUMBER
                                          , "STEP_ACTION_ID" NUMBER
                                          , "SOURCE_SPC_ID" NUMBER
                                          , "TARGET_SPC_ID" NUMBER
                                          , "CREATED" DATE
                                          , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                          , "MODIFIED" DATE
                                          , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                        )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON TABLE "FLW_STEP_ACTION_SPC_SYNC" IS 'Table to store the SPC sync step action details';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."ID" IS 'Primary key';
   --COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."SOURCE_TYPE_FLOW_ID" IS 'Source type flow id';
   --COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."TARGET_TYPE_FLOW_ID" IS 'Target type flow id';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."STEP_ACTION_ID" IS 'Step action id';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."SOURCE_SPC_ID" IS 'Source SPC id';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."TARGET_SPC_ID" IS 'Target SPC id';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."CREATED" IS 'Creation date';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."CREATED_BY" IS 'Creation user';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."MODIFIED" IS 'Modification date';
   COMMENT ON COLUMN "FLW_STEP_ACTION_SPC_SYNC"."MODIFIED_BY" IS 'Modification user'; 

--------------------------------------------------------
--  DDL for Index FLW_STEP_ACTION_SPC_SYNC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLW_STEP_ACTION_SPC_SYNC_PK" ON "FLW_STEP_ACTION_SPC_SYNC" ("ID") ;

--------------------------------------------------------
--  DDL for Trigger FLW_STEP_ACTION_SPC_SYNC_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "FLW_STEP_ACTION_SPC_SYNC_BIU" 
    before insert or update  
    on FLW_STEP_ACTION_SPC_SYNC 
    for each row
begin
    if inserting and :new.created is null then
        :new.created      := sysdate; 
        :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified      := sysdate; 
    :new.modified_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end FLW_STEP_ACTION_SPC_SYNC_BIU;

/
ALTER TRIGGER "FLW_STEP_ACTION_SPC_SYNC_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table FLW_STEP_ACTION_SPC_SYNC
--------------------------------------------------------

  --ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("SOURCE_TYPE_FLOW_ID" NOT NULL ENABLE);
  --ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("TARGET_TYPE_FLOW_ID" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("STEP_ACTION_ID" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("SOURCE_SPC_ID" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("TARGET_SPC_ID" NOT NULL ENABLE);  
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------

  --ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_FK1" FOREIGN KEY ("SOURCE_TYPE_FLOW_ID") REFERENCES "FLW_TYPE" ("ID") ENABLE;
  --ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_FK2" FOREIGN KEY ("TARGET_TYPE_FLOW_ID") REFERENCES "FLW_TYPE" ("ID") ENABLE;
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_FK3" FOREIGN KEY ("STEP_ACTION_ID") REFERENCES "FLW_TYPE_STEP_ACTION" ("ID") ENABLE;
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_FK4" FOREIGN KEY ("SOURCE_SPC_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE;
  ALTER TABLE "FLW_STEP_ACTION_SPC_SYNC" ADD CONSTRAINT "FLW_STEP_ACTION_SPC_SYNC_FK5" FOREIGN KEY ("TARGET_SPC_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE;