DROP TABLE "FLW_NOTIFICATION";
--------------------------------------------------------
--  DDL for Table FLW_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "FLW_NOTIFICATION" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                  , "NOTIF_TYPE" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                                  , "NOTIF_CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                                  , "NOTIF_FROM" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "NOTIF_TO" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "PLSQL_CODE" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                                  , "CREATED" DATE
                                  , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "MODIFIED" DATE
                                  , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP")  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON COLUMN "FLW_NOTIFICATION"."ID" IS 'ID of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."NOTIF_TYPE" IS 'Determine notification type (Ex: Email , SMS,..)';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."NOTIF_FROM" IS 'notifications sender';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."NOTIF_TO" IS 'notification Recipient';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."PLSQL_CODE" IS 'PL/SQL code to execute before sending the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."CREATED" IS 'Creation date of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."CREATED_BY" IS 'Creator of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."MODIFIED" IS 'Modification date of the notification';
   COMMENT ON COLUMN "FLW_NOTIFICATION"."MODIFIED_BY" IS 'Modifier of the notification';
--------------------------------------------------------
--  DDL for Index FLW_NOTIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLW_NOTIFICATION_PK" ON "FLW_NOTIFICATION" ("ID");
--------------------------------------------------------
--  DDL for Index FLW_NOTIFICATION_UN1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FLW_NOTIFICATION_UN1" ON "FLW_NOTIFICATION" ("NOTIF_CODE");
--------------------------------------------------------
--  DDL for Trigger FLW_NOTIFICATION_BIU_TRG
--------------------------------------------------------

 CREATE OR REPLACE EDITIONABLE TRIGGER "FLW_NOTIFICATION_BIU" 
    before insert or update  
    on FLW_NOTIFICATION 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end FLW_NOTIFICATION_BIU;
 /
ALTER TRIGGER "FLW_NOTIFICATION_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table FLW_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("NOTIF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("NOTIF_CODE" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("NOTIF_FROM" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "FLW_NOTIFICATION" ADD CONSTRAINT "FLW_NOTIFICATION_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "FLW_NOTIFICATION" ADD CONSTRAINT "FLW_NOTIFICATION_UN1" UNIQUE ("NOTIF_CODE") USING INDEX  ENABLE;

--------------------------------------------------------

