DROP TABLE "HLP_CONFIG_LANG";
--------------------------------------------------------
--  DDL for Table HLP_CONFIG_LANG
--------------------------------------------------------

  CREATE TABLE "HLP_CONFIG_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                  , "CONFIG_ID" NUMBER
                                  , "LANG_ID" NUMBER
                                  , "TITLE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "TEXT" CLOB
                                  , "CREATED" DATE
                                  , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "MODIFIED" DATE
                                  , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  )  DEFAULT COLLATION "USING_NLS_COMP";
--------------------------------------------------------
--  DDL for Index HLP_CONFIG_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HLP_CONFIG_LANG_PK" ON "HLP_CONFIG_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index HLP_CONFIG_LANG_IDX1
--------------------------------------------------------

  CREATE INDEX "HLP_CONFIG_LANG_UNIX1" ON "HLP_CONFIG_LANG" ("CONFIG_ID","LANG_ID");

--------------------------------------------------------
--  DDL for Trigger HLP_CONFIG_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HLP_CONFIG_LANG_BIU" 
    before insert or update  
    on HLP_CONFIG_LANG 
    for each row
begin
  if inserting and :new.created is null then
      :new.created      := sysdate; 
      :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
  end if; 
      :new.modified     := sysdate; 
      :new.modified_by  := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end HLP_CONFIG_LANG_BIU; 
/
ALTER TRIGGER "HLP_CONFIG_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table HLP_CONFIG_LANG
--------------------------------------------------------

  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("CONFIG_ID" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG_LANG" ADD CONSTRAINT "HLP_CONFIG_LANG_PK" PRIMARY KEY ("ID") USING INDEX "HLP_CONFIG_LANG_PK"  ENABLE;
  ALTER TABLE "HLP_CONFIG_LANG" ADD CONSTRAINT "HLP_CONFIG_LANG_UNIX1" UNIQUE ("CONFIG_ID","LANG_ID") USING INDEX "HLP_CONFIG_LANG_UNIX1"  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table HLP_CONFIG_LANG
--------------------------------------------------------

  ALTER TABLE "HLP_CONFIG_LANG" ADD CONSTRAINT "HLP_CONFIG_LANG_FK1" FOREIGN KEY ("CONFIG_ID") REFERENCES "HLP_CONFIG" ("ID") ENABLE;
  ALTER TABLE "HLP_CONFIG_LANG" ADD CONSTRAINT "HLP_CONFIG_LANG_FK2" FOREIGN KEY ("LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
