DROP TABLE "HLP_CONFIG";
--------------------------------------------------------
--  DDL for Table HLP_CONFIG
--------------------------------------------------------

  CREATE TABLE "HLP_CONFIG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                            , "APP_ID" NUMBER
                            , "PAGE_ID" NUMBER
                            , "CREATED" DATE
                            , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                            , "MODIFIED" DATE
                            , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                            )  DEFAULT COLLATION "USING_NLS_COMP";
--------------------------------------------------------
--  DDL for Index HLP_CONFIG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HLP_CONFIG_PK" ON "HLP_CONFIG" ("ID");
--------------------------------------------------------
--  DDL for Index HLP_CONFIG_IDX1
--------------------------------------------------------

  CREATE INDEX "HLP_CONFIG_UNIX1" ON "HLP_CONFIG" ("APP_ID","PAGE_ID");

--------------------------------------------------------
--  DDL for Trigger HLP_CONFIG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HLP_CONFIG_BIU" 
    before insert or update  
    on HLP_CONFIG 
    for each row
begin
  if inserting and :new.created is null then
      :new.created      := sysdate; 
      :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
  end if; 
      :new.modified     := sysdate; 
      :new.modified_by  := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end HLP_CONFIG_BIU; 
/
ALTER TRIGGER "HLP_CONFIG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table HLP_CONFIG
--------------------------------------------------------

  ALTER TABLE "HLP_CONFIG" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" MODIFY ("PAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "HLP_CONFIG" ADD CONSTRAINT "HLP_CONFIG_PK" PRIMARY KEY ("ID") USING INDEX "HLP_CONFIG_PK"  ENABLE;
  ALTER TABLE "HLP_CONFIG" ADD CONSTRAINT "HLP_CONFIG_UNIX1" UNIQUE ("APP_ID","PAGE_ID") USING INDEX "HLP_CONFIG_UNIX1"  ENABLE;
