DROP TABLE "OBJ_FILE";
--------------------------------------------------------
--  DDL for Table OBJ_FILE
--------------------------------------------------------

CREATE TABLE "OBJ_FILE" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
                        "REF_TYPE_ID" NUMBER,
                        "REF_ID" NUMBER,
                        "FILE_NAME" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
                        "FILE_SIZE" NUMBER,
                        "OBJECT" BLOB, 
                        "MIME_TYPE" VARCHAR2(500) COLLATE "USING_NLS_COMP",
                        "CREATED" DATE,
                        "CREATED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP",
                        "MODIFIED" DATE,
                        "MODIFIED_BY" VARCHAR2(100) COLLATE "USING_NLS_COMP"
                        )  DEFAULT COLLATION "USING_NLS_COMP" ;
--------------------------------------------------------
--  DDL for Index OBJ_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "OBJ_FILE_PK" ON "OBJ_FILE" ("ID");
--------------------------------------------------------
--  DDL for Trigger OBJ_FILE_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "OBJ_FILE_BIU" 
    before insert or update  
    on OBJ_FILE
    for each row 
begin 
    if inserting then 
        :new.created    := sysdate; 
        :new.created_by := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified       := sysdate; 
    :new.modified_by    := coalesce(sys_context('APEX$SESSION','APP_USER'),user); 
end OBJ_FILE_BIU; 


/
ALTER TRIGGER "OBJ_FILE_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJ_FILE
--------------------------------------------------------

  ALTER TABLE "OBJ_FILE" MODIFY ("REF_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "OBJ_FILE" MODIFY ("REF_ID" NOT NULL ENABLE);
  ALTER TABLE "OBJ_FILE" MODIFY ("FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "OBJ_FILE" MODIFY ("OBJECT" NOT NULL ENABLE);
  ALTER TABLE "OBJ_FILE" MODIFY ("MIME_TYPE" NOT NULL ENABLE);

  ALTER TABLE "OBJ_FILE" ADD CONSTRAINT "INC_OBJETCS_STORAGE_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------

    ALTER TABLE "OBJ_FILE" ADD CONSTRAINT "OBJ_FILE_FK1" FOREIGN KEY ("REF_TYPE_ID") REFERENCES "SPC_REF_TYPE" ("ID") ENABLE;
