DROP TABLE "SPC_REPORT_LANG";
--------------------------------------------------------
--  DDL for Table SPC_REPORT_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_REPORT_LANG" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                 , "REPORT_ID" NUMBER
                                 , "REPORT_LANG_ID" NUMBER
                                 , "REPORT_NAME" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                 , "DETAIL" VARCHAR2(1000) COLLATE "USING_NLS_COMP" 
                                 , "CREATED" DATE
                                 , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP" 
                                 , "MODIFIED" DATE 
                                 , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP" 
                                )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON TABLE "SPC_REPORT_LANG" IS 'Table of translations for reports';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."ID" IS 'Primary key';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."REPORT_ID" IS 'Report ID reference table SPC_REPORT';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."REPORT_LANG_ID" IS 'Language ID reference table SPC_LANG';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."REPORT_NAME" IS 'Report name';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."DETAIL" IS 'Report description';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."CREATED" IS 'Creation date';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."CREATED_BY" IS 'Creation user';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."MODIFIED" IS 'Modification date';
   COMMENT ON COLUMN "SPC_REPORT_LANG"."MODIFIED_BY" IS 'Modification user';

--------------------------------------------------------
--  DDL for Index SPC_REPORT_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_LANG_PK" ON "SPC_REPORT_LANG" ("ID");

--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_LANG_UK1" ON "SPC_REPORT_LANG" ("REPORT_ID", "REPORT_LANG_ID");

--------------------------------------------------------
--  DDL for Trigger SPC_REPORT_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_REPORT_LANG_BIU" 
    before insert or update  
    on SPC_REPORT_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created      := sysdate; 
        :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified      := sysdate; 
    :new.modified_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_REPORT_LANG_BIU;

/
ALTER TRIGGER "SPC_REPORT_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_REPORT_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("REPORT_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("REPORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_LANG" ADD CONSTRAINT "SPC_REPORT_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------
  ALTER TABLE "SPC_REPORT_LANG" ADD CONSTRAINT "SPC_REPORT_LANG_FK1" FOREIGN KEY ("REPORT_ID") REFERENCES "SPC_REPORT" ("ID") ENABLE;
  ALTER TABLE "SPC_REPORT_LANG" ADD CONSTRAINT "SPC_REPORT_LANG_FK2" FOREIGN KEY ("REPORT_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
