DROP TABLE "SPC_FORMAT";
--------------------------------------------------------
--  DDL for Table SPC_FORMAT
--------------------------------------------------------

  CREATE TABLE "SPC_FORMAT" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                            , "CLASS" VARCHAR2(250) COLLATE "USING_NLS_COMP"
                            , "DESCRIPTION" VARCHAR2(2000) COLLATE "USING_NLS_COMP"
                            , "FORMAT" VARCHAR2(2000) COLLATE "USING_NLS_COMP"
                            )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON TABLE "SPC_FORMAT" IS 'This table contains the format for the diferent specificities';
   COMMENT ON COLUMN "SPC_FORMAT"."ID" IS 'Unique identifier for the table';
   COMMENT ON COLUMN "SPC_FORMAT"."CLASS" IS 'Class used to identify the specificity to be formatted'; 
   COMMENT ON COLUMN "SPC_FORMAT"."DESCRIPTION" IS 'Description of the format';
   COMMENT ON COLUMN "SPC_FORMAT"."FORMAT" IS 'Format to be used to format the specificity';
--------------------------------------------------------
--  DDL for Index SPC_FORMAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_FORMAT_PK" ON "SPC_FORMAT" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_FORMAT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_FORMAT_UK1" ON "SPC_FORMAT" ("CLASS");
--------------------------------------------------------
--  Constraints for Table SPC_FORMAT
--------------------------------------------------------

  ALTER TABLE "SPC_FORMAT" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SPC_FORMAT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_FORMAT" MODIFY ("FORMAT" NOT NULL ENABLE);

  ALTER TABLE "SPC_FORMAT" ADD CONSTRAINT "SPC_FORMAT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_FORMAT" ADD CONSTRAINT "SPC_FORMAT_UK1" UNIQUE ("CLASS") USING INDEX  ENABLE;