DROP TABLE "SPC_REPORT";
--------------------------------------------------------
--  DDL for Table SPC_REPORT
--------------------------------------------------------

  CREATE TABLE "SPC_REPORT" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                            , "TYPE_REF_ID" NUMBER
                            , "ACTIVE_IND" NUMBER DEFAULT 1
                            , "ROLE_IDS" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                            , "CREATED" DATE
                            , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                            , "MODIFIED" DATE
                            , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                        )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON TABLE "SPC_REPORT" IS 'Table of dynamic reports';
   COMMENT ON COLUMN "SPC_REPORT"."ID" IS 'Primary key';
   COMMENT ON COLUMN "SPC_REPORT"."TYPE_REF_ID " IS 'Type reference id, references table SPC_REF_TYPE';
   COMMENT ON COLUMN "SPC_REPORT"."ACTIVE_IND" IS 'Active indicator';
   COMMENT ON COLUMN "SPC_REPORT"."ROLE_IDS" IS 'Role ids that can access the report';
   COMMENT ON COLUMN "SPC_REPORT"."CREATED" IS 'Creation date';
   COMMENT ON COLUMN "SPC_REPORT"."CREATED_BY" IS 'Creation user';
   COMMENT ON COLUMN "SPC_REPORT"."MODIFIED" IS 'Modification date';
   COMMENT ON COLUMN "SPC_REPORT"."MODIFIED_BY" IS 'Modification user'; 

--------------------------------------------------------
--  DDL for Index SPC_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_PK" ON "SPC_REPORT" ("ID") ;

--------------------------------------------------------
--  DDL for Trigger SPC_REPORT_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_REPORT_BIU" 
    before insert or update  
    on SPC_REPORT 
    for each row
begin
    if inserting and :new.created is null then
        :new.created      := sysdate; 
        :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified      := sysdate; 
    :new.modified_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_REPORT_BIU;

/
ALTER TRIGGER "SPC_REPORT_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_REPORT
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT" MODIFY ("TYPE_REF_ID " NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT" ADD CONSTRAINT "SPC_REPORT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_REPORT" ADD CONSTRAINT "SPC_REPORT_CHK1" CHECK (ACTIVE_IND in (0, 1)) ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT" ADD CONSTRAINT "SPC_REPORT_FK1" FOREIGN KEY ("TYPE_REF_ID ") REFERENCES "SPC_REF_TYPE" ("ID") ENABLE;