DROP TABLE "SPC_LOV";
--------------------------------------------------------
--  DDL for Table SPC_LOV
--------------------------------------------------------

  CREATE TABLE "SPC_LOV" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                        , "LIST_GROUP" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                        , "LIST_CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                        , "VALUE_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP"                
                        --, "DESCRIPTION_EN" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" --- lang
                        --, "DESCRIPTION_FR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP"
                        , "ACTIVE_IND" NUMBER(1,0) DEFAULT 1        
                        , "SYSTEM_IND" NUMBER DEFAULT 0   
                        --, "DISPLAY_ONLY_IND" NUMBER DEFAULT 0                          
                        , "CREATED" DATE DEFAULT sysdate
                        , "CREATED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT user
                        , "MODIFIED" DATE DEFAULT sysdate
                        , "MODIFIED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT user
                        --** WILL BE REMOVED **--
                        --, "ABREVIATION_EN" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP"
                        --, "ABREVIATION_FR" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP"
                        --, "NUM_VALUE" NUMBER     
                        --, "PARENT_ID" NUMBER
                        --, "REF_PARENT_ID" NUMBER
                        --, "TERME_PAIEMENT" NUMBER
                        --, "NOM_TABLE" VARCHAR2(30) COLLATE "USING_NLS_COMP"
                        --, "NOM_COL" VARCHAR2(30) COLLATE "USING_NLS_COMP"
                        --, "UNITE_AFF_ID" NUMBER DEFAULT ON NULL sys_context('LAFABRIQUE_CTX','UNITE_AFFAIRE_ID')
                        )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_LOV"."LIST_GROUP" IS 'Allows the list record to be organized by group';
   COMMENT ON COLUMN "SPC_LOV"."LIST_CODE" IS 'Code of the list to which the record belongs';
   COMMENT ON COLUMN "SPC_LOV"."VALUE_CODE" IS 'Allows the list option to be identify by a code';
   COMMENT ON COLUMN "SPC_LOV"."ACTIVE_IND" IS 'Indicates if the list option is active or inactive';
   COMMENT ON COLUMN "SPC_LOV"."SYSTEM_IND" IS 'Indicates if the list option is created by default and cannot be deleted by users';
 
   COMMENT ON COLUMN "SPC_LOV"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_LOV"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_LOV"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_LOV"."MODIFIED_BY" IS 'allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_LOV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_PK" ON "SPC_LOV" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_LOV_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_UK1" ON "SPC_LOV" ("LIST_GROUP", "LIST_CODE", "VALUE_CODE");
--------------------------------------------------------
--  DDL for Trigger SPC_LOV_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_LOV_BIU" 
    before insert or update  
    on SPC_LOV 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_LOV_BIU;

ALTER TRIGGER "SPC_LOV_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_LOV
--------------------------------------------------------

  --ALTER TABLE "SPC_LOV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("LIST_GROUP" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("LIST_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("VALUE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("SYSTEM_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" ADD CONSTRAINT "SPC_LOV_PK" PRIMARY KEY ("ID") USING INDEX "SPC_LOV_PK"  ENABLE;
  ALTER TABLE "SPC_LOV" ADD CONSTRAINT "SPC_LOV_UK1" UNIQUE ("LIST_GROUP", "LIST_CODE", "VALUE_CODE") USING INDEX  ENABLE;
