DROP TABLE "SPC_DEFINITION_REPORT";
--------------------------------------------------------
--  DDL for Table SPC_DEFINITION_REPORT
--------------------------------------------------------

  CREATE TABLE "SPC_DEFINITION_REPORT" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                        , "SPC_ID" NUMBER
                        , "REF_TYPE_ID" NUMBER
                        )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON TABLE "SPC_DEFINITION_REPORT" IS 'To store wich specs are used in wich type of reference';
   COMMENT ON COLUMN "SPC_DEFINITION_REPORT"."ID" IS 'Unique identifier';
   COMMENT ON COLUMN "SPC_DEFINITION_REPORT"."SPC_ID" IS 'Spec ID';
   COMMENT ON COLUMN "SPC_DEFINITION_REPORT"."REF_TYPE_ID" IS 'Reference type ID';
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_REPORT_PK" ON "SPC_DEFINITION_REPORT" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_REPORT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_REPORT_UK1" ON "SPC_DEFINITION_REPORT" ("SPC_ID","REF_TYPE_ID");

--------------------------------------------------------
--  Constraints for Table SPC_DEFINITION_REPORT
--------------------------------------------------------


  ALTER TABLE "SPC_DEFINITION_REPORT" MODIFY ("SPC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_REPORT" MODIFY ("REF_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_REPORT" ADD CONSTRAINT "SPC_DEFINITION_REPORT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_DEFINITION_REPORT" ADD CONSTRAINT "SPC_DEFINITION_REPORT_UK1" UNIQUE ("SPC_ID", "REF_TYPE_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION_REPORT
--------------------------------------------------------

  ALTER TABLE "SPC_DEFINITION_REPORT" ADD CONSTRAINT "SPC_DEFINITION_REPORT_FK1" FOREIGN KEY ("SPC_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE;
  ALTER TABLE "SPC_DEFINITION_REPORT" ADD CONSTRAINT "SPC_DEFINITION_REPORT_FK2" FOREIGN KEY ("REF_TYPE_ID") REFERENCES "SPC_REF_TYPE" ("ID") ENABLE;
