DROP TABLE "SPC_REPORT_DETAIL_LANG";
--------------------------------------------------------
--  DDL for Table SPC_REPORT_DETAIL_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_REPORT_DETAIL_LANG" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                        , "REPORT_DETAIL_ID" NUMBER
                                        , "REPORT_LANG_ID" NUMBER
                                        , "LABEL_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                                        , "CREATED" DATE
                                        , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                        , "MODIFIED" DATE
                                        , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                      )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON TABLE "SPC_REPORT_DETAIL_LANG" IS 'Table of report detail language';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."ID" IS 'Primary key';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."REPORT_DETAIL_ID" IS 'Report detail id references SPC_REPORT_DETAIL';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."REPORT_LANG_ID" IS 'Report language id references SPC_LANG';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."LABEL_NAME" IS 'Label name in the language';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."CREATED" IS 'Creation date';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."CREATED_BY" IS 'Creation user';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."MODIFIED" IS 'Modification date';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL_LANG"."MODIFIED_BY" IS 'Modification user';
--------------------------------------------------------
--  DDL for Index SPC_REPORT_DETAIL_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_DETAIL_LANG_PK" ON "SPC_REPORT_DETAIL_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_REPORT_DETAIL_LANG_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_DETAIL_LANG_UK1" ON "SPC_REPORT_DETAIL_LANG" ("REPORT_DETAIL_ID", "REPORT_LANG_ID");

--------------------------------------------------------
--  DDL for Trigger SPC_REPORT_DETAIL_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_REPORT_DETAIL_LANG_BIU" 
    before insert or update  
    on SPC_REPORT_DETAIL_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created      := sysdate; 
        :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified      := sysdate; 
    :new.modified_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_REPORT_DETAIL_LANG_BIU;

/
ALTER TRIGGER "SPC_REPORT_DETAIL_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_REPORT_DETAIL_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("REPORT_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("REPORT_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("LABEL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);

  ALTER TABLE "SPC_REPORT_DETAIL_LANG" ADD CONSTRAINT "SPC_REPORT_DETAIL_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" ADD CONSTRAINT "SPC_REPORT_DETAIL_LANG_UK1" UNIQUE ("REPORT_DETAIL_ID", "REPORT_LANG_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_REPORT_DETAIL_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT_DETAIL_LANG" ADD CONSTRAINT "SPC_REPORT_DETAIL_LANG_FK1" FOREIGN KEY ("REPORT_DETAIL_ID") REFERENCES "SPC_REPORT_DETAIL" ("ID") ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL_LANG" ADD CONSTRAINT "SPC_REPORT_DETAIL_LANG_FK2" FOREIGN KEY ("REPORT_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
