DROP TABLE "SPC_GROUP_DEFINITION";
--------------------------------------------------------
--  DDL for Table SPC_GROUP_DEFINITION
--------------------------------------------------------

  CREATE TABLE "SPC_GROUP_DEFINITION" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                     , "GROUP_CODE" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                     , "CREATED" DATE
                                     , "CREATED_BY" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     , "MODIFIED" DATE
                                     , "MODIFIED_BY" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON TABLE "SPC_GROUP_DEFINITION" IS 'Table to define the groups of specificities';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."ID" IS 'Unique identifier for the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."GROUP_CODE" IS 'Allows the user to group specificities by code';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."DESCRIPTION" IS 'Name or small description for the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."CREATED" IS 'Date when the group was created';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."CREATED_BY" IS 'User who created the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."MODIFIED" IS 'Date when the group was modified';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."MODIFIED_BY" IS 'User who modified the group';
--------------------------------------------------------
--  DDL for Index SPC_GROUP_DEFINITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_GROUP_DEFINITION_PK" ON "SPC_GROUP_DEFINITION" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_GROUP_DEFINITION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_GROUP_DEFINITION_UK1" ON "SPC_GROUP_DEFINITION" ("GROUP_CODE");
--------------------------------------------------------
--  DDL for Trigger SPC_GROUP_DEFINITION_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_GROUP_DEFINITION_BIU" 
    before insert or update  
    on SPC_GROUP_DEFINITION 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_GROUP_DEFINITION_BIU;

ALTER TRIGGER "SPC_GROUP_DEFINITION_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_GROUP_DEFINITION
--------------------------------------------------------

  ALTER TABLE "SPC_GROUP_DEFINITION" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_GROUP_DEFINITION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_GROUP_DEFINITION" ADD CONSTRAINT "SPC_GROUP_DEFINITION_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_GROUP_DEFINITION" ADD CONSTRAINT "SPC_GROUP_DEFINITION_UK1" UNIQUE ("GROUP_CODE") USING INDEX  ENABLE;