DROP TABLE "SPC_REPORT_DETAIL";
--------------------------------------------------------
--  DDL for Table SPC_REPORT_DETAIL
--------------------------------------------------------

  CREATE TABLE "SPC_REPORT_DETAIL" ( "ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                   , "REPORT_ID" NUMBER
                                   , "SEQ_NO" NUMBER
                                   , "SPC_IND" NUMBER
                                   , "COLUMN_VALUE" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                   , "ACTIVE_IND" NUMBER DEFAULT 1
                                   , "ORDER_BY_IND" NUMBER DEFAULT 0
                                   , "GROUP_BY_IND" NUMBER DEFAULT 0
                                   , "DISPLAY_IND" NUMBER DEFAULT 1 
                                   , "OPERATOR_COMP" NUMBER
                                   , "VALUE_REF_COMP" VARCHAR2(100) COLLATE "USING_NLS_COMP"
                                   , "CREATED" DATE
                                   , "CREATED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                   , "MODIFIED" DATE
                                   , "MODIFIED_BY" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  )  DEFAULT COLLATION "USING_NLS_COMP" ;

   COMMENT ON TABLE "SPC_REPORT_DETAIL" IS 'Configuration table of columns to be displayed in the report';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."ID" IS 'Primary key';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."REPORT_ID" IS 'Foreign key to SPC_REPORT';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."SEQ_NO" IS 'Sequence number';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."SPC_IND" IS 'Indicate if the column is a specificity or not';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."COLUMN_VALUE" IS 'Column name';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."ACTIVE_IND" IS 'Indicate if the column is active or not';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."ORDER_BY_IND" IS 'Indicate if the column is ordered or not';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."GROUP_BY_IND" IS 'Indicate if the column is grouped or not';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."DISPLAY_IND" IS 'Indicate if the column is displayed or not';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."OPERATOR_COMP" IS 'Operator of comparison';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."VALUE_REF_COMP" IS 'Column name of comparison';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."CREATED" IS 'Creation date';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."CREATED_BY" IS 'Creation user';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."MODIFIED" IS 'Modification date';
   COMMENT ON COLUMN "SPC_REPORT_DETAIL"."MODIFIED_BY" IS 'Modification user';
--------------------------------------------------------
--  DDL for Index SPC_REPORT_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_DETAIL_PK" ON "SPC_REPORT_DETAIL" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_REPORT_DETAIL_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_DETAIL_UK1" ON "SPC_REPORT_DETAIL" ("REPORT_ID", "SEQ_NO");

--------------------------------------------------------
--  DDL for Index SPC_REPORT_DETAIL_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REPORT_DETAIL_UK2" ON "SPC_REPORT_DETAIL" ("REPORT_ID", "COLUMN_VALUE");

--------------------------------------------------------
--  DDL for Trigger SPC_REPORT_DETAIL_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_REPORT_DETAIL_BIU" 
    before insert or update  
    on SPC_REPORT_DETAIL 
    for each row
begin
    if inserting and :new.created is null then
        :new.created      := sysdate; 
        :new.created_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified      := sysdate; 
    :new.modified_by   := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_REPORT_DETAIL_BIU;

/
ALTER TRIGGER "SPC_REPORT_DETAIL_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_REPORT_DETAIL
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("SPC_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("COLUMN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("ORDER_BY_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("GROUP_BY_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("DISPLAY_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("OPERATOR_COMP" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("VALUE_REF_COMP" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REPORT_DETAIL" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);

  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;

  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_UK1" UNIQUE ("REPORT_ID", "SEQ_NO") USING INDEX  ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_UK2" UNIQUE ("REPORT_ID", "COLUMN_VALUE") USING INDEX  ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK1" CHECK (SPC_IND in (0, 1)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK2" CHECK (ACTIVE_IND in (0, 1)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK3" CHECK (ORDER_BY_IND in (0, 1, 2)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK4" CHECK (GROUP_BY_IND in (0, 1)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK5" CHECK (DISPLAY_IND in (0, 1)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK6" CHECK (OPERATOR_COMP in (0, 1, 2, 3, 4)) ENABLE;
  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_CHK7" CHECK (VALUE_REF_COMP in (0, 1)) ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_REPORT_DETAIL
--------------------------------------------------------

  ALTER TABLE "SPC_REPORT_DETAIL" ADD CONSTRAINT "SPC_REPORT_DETAIL_FK1" FOREIGN KEY ("REPORT_ID") REFERENCES "SPC_REPORT" ("ID") ENABLE;
