DROP TABLE "SPC_LANG";
--------------------------------------------------------
--  DDL for Table SPC_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                        , "LANG_CODE" VARCHAR2(5) COLLATE "USING_NLS_COMP"
                        , "DESCRIPTION" VARCHAR2(250) COLLATE "USING_NLS_COMP"
                        , "DEFAULT_LANG_IND" NUMBER DEFAULT 0
                        , "CREATED" DATE 
                        , "CREATED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                        , "MODIFIED" DATE
                        , "MODIFIED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                        )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_LANG"."LANG_CODE" IS 'Allows the language to be identify by a code';
   COMMENT ON COLUMN "SPC_LANG"."DESCRIPTION" IS 'Display name of the language';
   COMMENT ON COLUMN "SPC_LANG"."DEFAULT_LANG_IND" IS 'Indicates which language is displayed by default';
   COMMENT ON COLUMN "SPC_LANG"."CREATED" IS 'Date and time the record was created';
   COMMENT ON COLUMN "SPC_LANG"."CREATED_BY" IS 'User who created the record';
   COMMENT ON COLUMN "SPC_LANG"."MODIFIED" IS 'Date and time the record was last modified';
   COMMENT ON COLUMN "SPC_LANG"."MODIFIED_BY" IS 'User who last modified the record';
--------------------------------------------------------
--  DDL for Index SPC_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LANG_PK" ON "SPC_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LANG_UK1" ON "SPC_LANG" ("LANG_CODE");
--------------------------------------------------------
--  DDL for Trigger SPC_DATA_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_LANG_BIU" 
    before insert or update  
    on SPC_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DATA_BIU;

ALTER TRIGGER "SPC_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_LANG
--------------------------------------------------------


  ALTER TABLE "SPC_LANG" MODIFY ("LANG_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_LANG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_LANG" ADD CONSTRAINT "SPC_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_LANG" ADD CONSTRAINT "SPC_LANG_UK1" UNIQUE ("LANG_CODE") USING INDEX  ENABLE;