DROP TABLE "SPC_DEFINITION_LANG";
--------------------------------------------------------
--  DDL for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_DEFINITION_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                    , "SPC_LANG_ID" NUMBER
                                    , "SPC_DEFINITION_ID" NUMBER 
                                    , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                    , "HELP_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                                    , "CREATED" DATE
                                    , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                    , "MODIFIED" DATE
                                    , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                    )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."SPC_LANG_ID" IS 'Reference the ID of language in the spc_lang table';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."SPC_DEFINITION_ID" IS 'Reference the ID of the specificity in the spc_definition table';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."DESCRIPTION" IS 'Description of the specificity in the chosen language';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."HELP_TEXT" IS 'Help text of the specificity in the chosen language';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."MODIFIED_BY" IS 'Allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_LANG_PK" ON "SPC_DEFINITION_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_LANG_UK1" ON "SPC_DEFINITION_LANG" ("SPC_LANG_ID","SPC_DEFINITION_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_DEFINITION_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_DEFINITION_LANG_BIU" 
    before insert or update  
    on SPC_DEFINITION_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DEFINITION_LANG_BIU;

ALTER TRIGGER "SPC_DEFINITION_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  --ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("SPC_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("SPC_DEFINITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_UK1" UNIQUE ("SPC_LANG_ID","SPC_DEFINITION_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_FK1" FOREIGN KEY ("SPC_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_FK2" FOREIGN KEY ("SPC_DEFINITION_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE;