DROP TABLE "SPC_LOV_LANG";
--------------------------------------------------------
--  DDL for Table SPC_LOV_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_LOV_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                             , "SPC_LANG_ID" NUMBER
                             , "SPC_LOV_ID" NUMBER 
                             , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                             , "CREATED" DATE
                             , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                             , "MODIFIED" DATE
                             , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                             )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_LOV_LANG"."SPC_LANG_ID" IS 'Reference the ID of language in the spc_lang table';
   COMMENT ON COLUMN "SPC_LOV_LANG"."SPC_LOV_ID" IS 'Reference the ID of the list record in the spc_lov table';
   COMMENT ON COLUMN "SPC_LOV_LANG"."DESCRIPTION" IS 'Description of the list record in the chosen language';
   COMMENT ON COLUMN "SPC_LOV_LANG"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_LOV_LANG"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_LOV_LANG"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_LOV_LANG"."MODIFIED_BY" IS 'Allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_LOV_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_LANG_PK" ON "SPC_LOV_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_LOV_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_LANG_UK1" ON "SPC_LOV_LANG" ("SPC_LANG_ID","SPC_LOV_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_LOV_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_LOV_LANG_BIU" 
    before insert or update  
    on SPC_LOV_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_LOV_LANG_BIU;

ALTER TRIGGER "SPC_LOV_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_LOV_LANG
--------------------------------------------------------

  --ALTER TABLE "SPC_LOV_LANG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("SPC_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("SPC_LOV_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_UK1" UNIQUE ("SPC_LANG_ID","SPC_LOV_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_LOV_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_FK1" FOREIGN KEY ("SPC_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_FK2" FOREIGN KEY ("SPC_LOV_ID") REFERENCES "SPC_LOV" ("ID") ENABLE;