DROP TABLE "SPC_DATA";
--------------------------------------------------------
--  DDL for Table SPC_DATA
--------------------------------------------------------

  CREATE TABLE "SPC_DATA" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                          , "SPC_ID" NUMBER
                          , "REF_TYPE_ID" NUMBER --& NEW
                          , "REF_ID" NUMBER --& NEW
                          , "VALUE" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                          , "CREATED" DATE
                          , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                          , "MODIFIED" DATE
                          , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                          )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_DATA"."SPC_ID" IS 'Reference the ID of the definition for the specifity the record is being created';
   COMMENT ON COLUMN "SPC_DATA"."REF_TYPE_ID" IS 'References the type of object id the specificity is being stored';
   COMMENT ON COLUMN "SPC_DATA"."REF_ID" IS 'References the id of the object the specoficity is being stored';
   COMMENT ON COLUMN "SPC_DATA"."VALUE" IS 'Value to be stored for the specificity';
   COMMENT ON COLUMN "SPC_DATA"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_DATA"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_DATA"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_DATA"."MODIFIED_BY" IS 'allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index ID_SPC_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_SPC_DATA_PK" ON "SPC_DATA" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DATA_INDEX1
--------------------------------------------------------

  CREATE INDEX "SPC_DATA_INDEX1" ON "SPC_DATA" ("REF_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_DATA_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_DATA_BIU" 
    before insert or update  
    on SPC_DATA 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DATA_BIU;

ALTER TRIGGER "SPC_DATA_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_DATA
--------------------------------------------------------
  
  --ALTER TABLE "SPC_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("SPC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" ADD CONSTRAINT "ID_SPC_DATA_PK" PRIMARY KEY ("ID") USING INDEX "ID_SPC_DATA_PK"  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table SPC_DATA
--------------------------------------------------------

  ALTER TABLE "SPC_DATA" ADD CONSTRAINT "SPC_DATA_FK1" FOREIGN KEY ("SPC_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE
  ALTER TABLE "SPC_DATA" ADD CONSTRAINT "SPC_DATA_FK2" FOREIGN KEY ("REF_TYPE_ID") REFERENCES "SPC_REF_TYPE" ("ID") ENABLE
