DROP TABLE "SPC_REF_TYPE";
--------------------------------------------------------
--  DDL for Table SPC_REF_TYPE
--------------------------------------------------------

  CREATE TABLE "SPC_REF_TYPE" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                              , "TABLE_NAME" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                              , "CREATED" DATE
                              , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                              , "MODIFIED" DATE
                              , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                              )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_REF_TYPE"."ID" IS 'Unique ID for the reference type';
   COMMENT ON COLUMN "SPC_REF_TYPE"."TABLE_NAME" IS 'Table name for the reference type';
   COMMENT ON COLUMN "SPC_REF_TYPE"."CREATED" IS 'Date and time the record was created';
   COMMENT ON COLUMN "SPC_REF_TYPE"."CREATED_BY" IS 'User who created the record';
   COMMENT ON COLUMN "SPC_REF_TYPE"."MODIFIED" IS 'Date and time the record was last modified';
   COMMENT ON COLUMN "SPC_REF_TYPE"."MODIFIED_BY" IS 'User who last modified the record';

--------------------------------------------------------
--  DDL for Index ID_SPC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_SPC_REF_TYPE_PK" ON "SPC_REF_TYPE" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_REF_TYPE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_REF_TYPE_UK1" ON "SPC_REF_TYPE" ("TABLE_NAME");
--------------------------------------------------------
--  DDL for Index SPC_REF_TYPE_IDX1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_REF_TYPE_BIU" 
    before insert or update  
    on SPC_REF_TYPE 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_REF_TYPE_BIU;

ALTER TRIGGER "SPC_REF_TYPE_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_REF_TYPE
--------------------------------------------------------

  ALTER TABLE "SPC_REF_TYPE" MODIFY ("TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPC_REF_TYPE" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REF_TYPE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_REF_TYPE" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_REF_TYPE" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);

  ALTER TABLE "SPC_REF_TYPE" ADD CONSTRAINT "ID_SPC_REF_TYPE_PK" PRIMARY KEY ("ID") USING INDEX "ID_SPC_REF_TYPE_PK"  ENABLE;
  ALTER TABLE "SPC_REF_TYPE" ADD CONSTRAINT "SPC_REF_TYPE_UK1" UNIQUE ("TABLE_NAME") USING INDEX "SPC_REF_TYPE_UK1"  ENABLE;