/*@../Tables/SPC_VAL_COUNTER.sql
@../Tables/SPC_LANG.sql
@../Tables/SPC_LOV.sql
@../Tables/SPC_LOV_LANG.sql
@../Tables/SPC_GROUP_DEFINITION.sql
@../Tables/SPC_DEFINITION.sql
@../Tables/SPC_DEFINITION_LANG.sql
@../Tables/SPC_DATA.sql
@../Tables/SPC_FORMAT.sql
*/

--------------------------------------------------------
--$  DDL for Table SPC_VAL_COUNTER
--------------------------------------------------------

    CREATE TABLE "SPC_VAL_COUNTER" ("CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                                , "GREATEST_VALUE" NUMBER DEFAULT 0
                                , "YEAR" VARCHAR2(4) COLLATE "USING_NLS_COMP"
                                )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_VAL_COUNTER"."CODE" IS 'Allow users to reference the counter by the code in the specificities';
   COMMENT ON COLUMN "SPC_VAL_COUNTER"."GREATEST_VALUE" IS 'Current value of the greatest number for the counter';
   COMMENT ON COLUMN "SPC_VAL_COUNTER"."YEAR" IS 'Allows the counter to reset by year';
--------------------------------------------------------
--  DDL for Index INC_GREATEST_VAL_COUNTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INC_GREATEST_VAL_COUNTER_PK" ON "SPC_VAL_COUNTER" ("CODE", "YEAR");
--------------------------------------------------------
--  Constraints for Table SPC_VAL_COUNTER
--------------------------------------------------------

  ALTER TABLE "SPC_VAL_COUNTER" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_VAL_COUNTER" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "SPC_VAL_COUNTER" ADD CONSTRAINT "INC_GREATEST_VAL_COUNTER_PK" PRIMARY KEY ("CODE", "YEAR") USING INDEX  ENABLE;
--------------------------------------------------------
--$  DDL END SPC_VAL_COUNTER
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_LOV
--------------------------------------------------------

  CREATE TABLE "SPC_LOV" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                        , "LIST_GROUP" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                        , "LIST_CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                        , "VALUE_CODE" VARCHAR2(30) COLLATE "USING_NLS_COMP"                
                        --, "DESCRIPTION_EN" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP" --- lang
                        --, "DESCRIPTION_FR" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP"
                        , "ACTIVE_IND" NUMBER(1,0) DEFAULT 1        
                        , "SYSTEM_IND" NUMBER DEFAULT 0   
                        --, "DISPLAY_ONLY_IND" NUMBER DEFAULT 0                          
                        , "CREATED" DATE DEFAULT sysdate
                        , "CREATED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT user
                        , "MODIFIED" DATE DEFAULT sysdate
                        , "MODIFIED_BY" VARCHAR2(50) COLLATE "USING_NLS_COMP" DEFAULT user
                        --** WILL BE REMOVED **--
                        --, "ABREVIATION_EN" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP"
                        --, "ABREVIATION_FR" VARCHAR2(30 CHAR) COLLATE "USING_NLS_COMP"
                        --, "NUM_VALUE" NUMBER     
                        --, "PARENT_ID" NUMBER
                        --, "REF_PARENT_ID" NUMBER
                        --, "TERME_PAIEMENT" NUMBER
                        --, "NOM_TABLE" VARCHAR2(30) COLLATE "USING_NLS_COMP"
                        --, "NOM_COL" VARCHAR2(30) COLLATE "USING_NLS_COMP"
                        --, "UNITE_AFF_ID" NUMBER DEFAULT ON NULL sys_context('LAFABRIQUE_CTX','UNITE_AFFAIRE_ID')
                        )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_LOV"."LIST_GROUP" IS 'Allows the list record to be organized by group';
   COMMENT ON COLUMN "SPC_LOV"."LIST_CODE" IS 'Code of the list to which the record belongs';
   COMMENT ON COLUMN "SPC_LOV"."VALUE_CODE" IS 'Allows the list option to be identify by a code';
   COMMENT ON COLUMN "SPC_LOV"."ACTIVE_IND" IS 'Indicates if the list option is active or inactive';
   COMMENT ON COLUMN "SPC_LOV"."SYSTEM_IND" IS 'Indicates if the list option is created by default and cannot be deleted by users';
 
   COMMENT ON COLUMN "SPC_LOV"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_LOV"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_LOV"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_LOV"."MODIFIED_BY" IS 'allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_LOV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_PK" ON "SPC_LOV" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_LOV_INDEX1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_UK1" ON "SPC_LOV" ("LIST_GROUP", "LIST_CODE", "VALUE_CODE");
--------------------------------------------------------
--  DDL for Trigger SPC_LOV_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_LOV_BIU" 
    before insert or update  
    on SPC_LOV 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_LOV_BIU;
/
ALTER TRIGGER "SPC_LOV_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_LOV
--------------------------------------------------------

  --ALTER TABLE "SPC_LOV" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("LIST_GROUP" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("LIST_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("VALUE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("SYSTEM_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("ACTIVE_IND" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV" ADD CONSTRAINT "SPC_LOV_PK" PRIMARY KEY ("ID") USING INDEX "SPC_LOV_PK"  ENABLE;
  ALTER TABLE "SPC_LOV" ADD CONSTRAINT "SPC_LOV_UK1" UNIQUE ("LIST_GROUP", "LIST_CODE", "VALUE_CODE") USING INDEX  ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_LOV
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_LOV_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_LOV_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                             , "SPC_LANG_ID" NUMBER
                             , "SPC_LOV_ID" NUMBER 
                             , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                             , "CREATED" DATE
                             , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                             , "MODIFIED" DATE
                             , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                             )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_LOV_LANG"."SPC_LANG_ID" IS 'Reference the ID of language in the spc_lang table';
   COMMENT ON COLUMN "SPC_LOV_LANG"."SPC_LOV_ID" IS 'Reference the ID of the list record in the spc_lov table';
   COMMENT ON COLUMN "SPC_LOV_LANG"."DESCRIPTION" IS 'Description of the list record in the chosen language';
   COMMENT ON COLUMN "SPC_LOV_LANG"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_LOV_LANG"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_LOV_LANG"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_LOV_LANG"."MODIFIED_BY" IS 'Allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_LOV_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_LANG_PK" ON "SPC_LOV_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_LOV_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_LOV_LANG_UK1" ON "SPC_LOV_LANG" ("SPC_LANG_ID","SPC_LOV_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_LOV_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_LOV_LANG_BIU" 
    before insert or update  
    on SPC_LOV_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_LOV_LANG_BIU;
/
ALTER TRIGGER "SPC_LOV_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_LOV_LANG
--------------------------------------------------------

  --ALTER TABLE "SPC_LOV_LANG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("SPC_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("SPC_LOV_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_UK1" UNIQUE ("SPC_LANG_ID","SPC_LOV_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_LOV_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_FK1" FOREIGN KEY ("SPC_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
  ALTER TABLE "SPC_LOV_LANG" ADD CONSTRAINT "SPC_LOV_LANG_FK2" FOREIGN KEY ("SPC_LOV_ID") REFERENCES "SPC_LOV" ("ID") ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_LOV_LANG
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_GROUP_DEFINITION
--------------------------------------------------------

  CREATE TABLE "SPC_GROUP_DEFINITION" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                     , "GROUP_CODE" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                     , "CREATED" DATE
                                     , "CREATED_BY" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     , "MODIFIED" DATE
                                     , "MODIFIED_BY" VARCHAR2(150) COLLATE "USING_NLS_COMP"
                                     )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON TABLE "SPC_GROUP_DEFINITION" IS 'Table to define the groups of specificities';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."ID" IS 'Unique identifier for the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."GROUP_CODE" IS 'Allows the user to group specificities by code';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."DESCRIPTION" IS 'Name or small description for the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."CREATED" IS 'Date when the group was created';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."CREATED_BY" IS 'User who created the group';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."MODIFIED" IS 'Date when the group was modified';
   COMMENT ON COLUMN "SPC_GROUP_DEFINITION"."MODIFIED_BY" IS 'User who modified the group';
--------------------------------------------------------
--  DDL for Index SPC_GROUP_DEFINITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_GROUP_DEFINITION_PK" ON "SPC_GROUP_DEFINITION" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_GROUP_DEFINITION_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_GROUP_DEFINITION_UK1" ON "SPC_GROUP_DEFINITION" ("GROUP_CODE");
--------------------------------------------------------
--  DDL for Trigger SPC_GROUP_DEFINITION_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_GROUP_DEFINITION_BIU" 
    before insert or update  
    on SPC_GROUP_DEFINITION 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_GROUP_DEFINITION_BIU;
/
ALTER TRIGGER "SPC_GROUP_DEFINITION_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_GROUP_DEFINITION
--------------------------------------------------------

  ALTER TABLE "SPC_GROUP_DEFINITION" MODIFY ("GROUP_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_GROUP_DEFINITION" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_GROUP_DEFINITION" ADD CONSTRAINT "SPC_GROUP_DEFINITION_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_GROUP_DEFINITION" ADD CONSTRAINT "SPC_GROUP_DEFINITION_UK1" UNIQUE ("GROUP_CODE") USING INDEX  ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_GROUP_DEFINITION
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_FORMAT
--------------------------------------------------------

  CREATE TABLE "SPC_FORMAT" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                            , "CLASS" VARCHAR2(250) COLLATE "USING_NLS_COMP"
                            , "DESCRIPTION" VARCHAR2(2000) COLLATE "USING_NLS_COMP"
                            , "FORMAT" VARCHAR2(2000) COLLATE "USING_NLS_COMP"
                            )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON TABLE "SPC_FORMAT" IS 'This table contains the format for the diferent specificities';
   COMMENT ON COLUMN "SPC_FORMAT"."ID" IS 'Unique identifier for the table';
   COMMENT ON COLUMN "SPC_FORMAT"."CLASS" IS 'Class used to identify the specificity to be formatted'; 
   COMMENT ON COLUMN "SPC_FORMAT"."DESCRIPTION" IS 'Description of the format';
   COMMENT ON COLUMN "SPC_FORMAT"."FORMAT" IS 'Format to be used to format the specificity';
--------------------------------------------------------
--  DDL for Index SPC_FORMAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_FORMAT_PK" ON "SPC_FORMAT" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_FORMAT_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_FORMAT_UK1" ON "SPC_FORMAT" ("CLASS");
--------------------------------------------------------
--  Constraints for Table SPC_FORMAT
--------------------------------------------------------

  ALTER TABLE "SPC_FORMAT" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "SPC_FORMAT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_FORMAT" MODIFY ("FORMAT" NOT NULL ENABLE);

  ALTER TABLE "SPC_FORMAT" ADD CONSTRAINT "SPC_FORMAT_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_FORMAT" ADD CONSTRAINT "SPC_FORMAT_UK1" UNIQUE ("CLASS") USING INDEX  ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_FORMAT
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_DEFINITION
--------------------------------------------------------

  CREATE TABLE "SPC_DEFINITION" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                  , "APP_ID" NUMBER
                                  , "PAGE_ID" NUMBER 
                                  , "GROUP_DEF_ID" NUMBER 
                                  , "SPC_CODE" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                  , "DISP_SEQ" NUMBER 
                                  , "FIELD_TYPE" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                  , "COUNTER_CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP"
                                  , "MANDATORY_IND" NUMBER DEFAULT 0
                                  , "READ_ONLY_IND" NUMBER DEFAULT 0
                                  , "ACTIVE_IND" NUMBER DEFAULT 1
                                  , "SYSDATE_IND" NUMBER
                                  , "HELP_TEXT_IND" NUMBER DEFAULT 0
                                  , "PRINT_IND" NUMBER DEFAULT 1
                                  , "LIST_GROUP" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "LIST_CODE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "DEFAULT_VALUE" VARCHAR2(2000) COLLATE "USING_NLS_COMP"
                                  , "ITEM_SIZE" NUMBER
                                  , "ITEM_MAX_LENGTH" NUMBER
                                  , "FORMAT_ID" NUMBER
                                  --, "MAX_VALUE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  --, "MIN_VALUE" VARCHAR2(255) COLLATE "USING_NLS_COMP"
                                  , "CREATED" DATE
                                  , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                  , "MODIFIED" DATE
                                  , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                  )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_DEFINITION"."APP_ID" IS 'Application ID to relate to the specificity';
   COMMENT ON COLUMN "SPC_DEFINITION"."PAGE_ID" IS 'Page ID to relate to the specificity';
   COMMENT ON COLUMN "SPC_DEFINITION"."GROUP_DEF_ID" IS 'References the ID of the table SPC_GROUP_DEFINITION';
   COMMENT ON COLUMN "SPC_DEFINITION"."SPC_CODE" IS 'Allows the specificity to be identify by a code';
   COMMENT ON COLUMN "SPC_DEFINITION"."DISP_SEQ" IS 'Allows the specificities to be order by the sequence number';
   COMMENT ON COLUMN "SPC_DEFINITION"."FIELD_TYPE" IS 'Indicates the type of item that corresponds to the specificity (date,list,text,etc..)';
   COMMENT ON COLUMN "SPC_DEFINITION"."COUNTER_CODE" IS 'This column references the counter defined in SPC_VAL_COUNTER';
   COMMENT ON COLUMN "SPC_DEFINITION"."MANDATORY_IND" IS 'Flag for mandatory specificities';
   COMMENT ON COLUMN "SPC_DEFINITION"."READ_ONLY_IND" IS 'Flag for read only specificities';
   COMMENT ON COLUMN "SPC_DEFINITION"."SYSDATE_IND" IS 'Indicates if the specificity of date should have a validation (1: max date sysdate; 2: min date sysdate)';
   COMMENT ON COLUMN "SPC_DEFINITION"."ACTIVE_IND" IS 'Indicates if the specificity is active or inactive';
   COMMENT ON COLUMN "SPC_DEFINITION"."HELP_TEXT_IND" IS 'Indicates if the specificity has a help text';
   COMMENT ON COLUMN "SPC_DEFINITION"."PRINT_IND" IS 'Indicates if the specificity should be printed';
   COMMENT ON COLUMN "SPC_DEFINITION"."DEFAULT_VALUE" IS 'Allows the user to define a default value for the specificity';
   COMMENT ON COLUMN "SPC_DEFINITION"."ITEM_SIZE" IS 'Allows the user to define the size of the item';
   COMMENT ON COLUMN "SPC_DEFINITION"."ITEM_MAX_LENGTH" IS 'Allows the user to define the maximum length of the item';
   COMMENT ON COLUMN "SPC_DEFINITION"."FORMAT_ID" IS 'Allows the user to assign the format of the item';
   --COMMENT ON COLUMN "SPC_DEFINITION"."MAX_VALUE" IS ''; --?
   --COMMENT ON COLUMN "SPC_DEFINITION"."MIN_VALUE" IS ''; --?
   COMMENT ON COLUMN "SPC_DEFINITION"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_DEFINITION"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_DEFINITION"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_DEFINITION"."MODIFIED_BY" IS 'Allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index ID_SPC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_SPC_PK" ON "SPC_DEFINITION" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_UK1
--------------------------------------------------------

  --CREATE UNIQUE INDEX "SPC_DEFINITION_UK1" ON "SPC_DEFINITION" ("APP_ID", "PAGE_ID", "SPC_CODE");
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_IDX1
--------------------------------------------------------

  --CREATE INDEX "SPC_DEFINITION_IDX1" ON "SPC_DEFINITION" ("ID", "APP_ID", "PAGE_ID"/*, "SPC_CODE"*/);
--------------------------------------------------------
--  DDL for Trigger SPC_DEFINITION_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_DEFINITION_BIU" 
    before insert or update  
    on SPC_DEFINITION 
    for each row
begin
    if inserting and :new.created is null then
        select nvl(max(d.disp_seq) + 10, 10)
        into :new.disp_seq
        from spc_definition d
        where d.app_id = :new.app_id
        and   d.page_id = :new.page_id
        and   d.group_def_id = :new.group_def_id;

        :new.spc_code   := 'ITEM_' || :new.id;
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    if updating and :new.group_def_id != :old.group_def_id then
        select nvl(max(d.disp_seq) + 10, 10)
        into :new.disp_seq
        from spc_definition d
        where d.app_id = :new.app_id
        and   d.page_id = :new.page_id
        and   d.group_def_id = :new.group_def_id;
    end if;
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DEFINITION_BIU;
/
ALTER TRIGGER "SPC_DEFINITION_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_DEFINITION
--------------------------------------------------------

  --ALTER TABLE "SPC_DEFINITION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("APP_ID" NOT NULL ENABLE); 
  --ALTER TABLE "SPC_DEFINITION" MODIFY ("PAGE_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("SPC_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("DISP_SEQ" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("FIELD_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);

  ALTER TABLE "SPC_DEFINITION" ADD CONSTRAINT "ID_SPC_PK" PRIMARY KEY ("ID") USING INDEX "ID_SPC_PK"  ENABLE;
  ALTER TABLE "SPC_DEFINITION" ADD CONSTRAINT "SPC_DEFINITION_UK1" UNIQUE ("APP_ID", "PAGE_ID", "SPC_CODE") USING INDEX  ENABLE;
  
--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION
--------------------------------------------------------
  
  ALTER TABLE "SPC_DEFINITION" ADD CONSTRAINT "SPC_DEFINITION_FK1" FOREIGN KEY ("GROUP_DEF_ID") REFERENCES "SPC_GROUP_DEFINITION" ("ID") ENABLE;
  ALTER TABLE "SPC_DEFINITION" ADD CONSTRAINT "SPC_DEFINITION_FK2" FOREIGN KEY ("FORMAT_ID") REFERENCES "SPC_FORMAT" ("ID") ENABLE;
  --ALTER TABLE "SPC_DEFINITION" ADD CONSTRAINT "SPC_DEFINITION_FK3" FOREIGN KEY ("COUNTER_CODE") REFERENCES "SPC_VAL_COUNTER" ("CODE") ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_DEFINITION
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  CREATE TABLE "SPC_DEFINITION_LANG" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                                    , "SPC_LANG_ID" NUMBER
                                    , "SPC_DEFINITION_ID" NUMBER 
                                    , "DESCRIPTION" VARCHAR2(500) COLLATE "USING_NLS_COMP"
                                    , "HELP_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                                    , "CREATED" DATE
                                    , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                    , "MODIFIED" DATE
                                    , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                                    )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."SPC_LANG_ID" IS 'Reference the ID of language in the spc_lang table';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."SPC_DEFINITION_ID" IS 'Reference the ID of the specificity in the spc_definition table';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."DESCRIPTION" IS 'Description of the specificity in the chosen language';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."HELP_TEXT" IS 'Help text of the specificity in the chosen language';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_DEFINITION_LANG"."MODIFIED_BY" IS 'Allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_LANG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_LANG_PK" ON "SPC_DEFINITION_LANG" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DEFINITION_LANG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPC_DEFINITION_LANG_UK1" ON "SPC_DEFINITION_LANG" ("SPC_LANG_ID","SPC_DEFINITION_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_DEFINITION_LANG_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_DEFINITION_LANG_BIU" 
    before insert or update  
    on SPC_DEFINITION_LANG 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DEFINITION_LANG_BIU;
/
ALTER TRIGGER "SPC_DEFINITION_LANG_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  --ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("SPC_LANG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("SPC_DEFINITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_PK" PRIMARY KEY ("ID") USING INDEX  ENABLE;
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_UK1" UNIQUE ("SPC_LANG_ID","SPC_DEFINITION_ID") USING INDEX  ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table SPC_DEFINITION_LANG
--------------------------------------------------------

  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_FK1" FOREIGN KEY ("SPC_LANG_ID") REFERENCES "SPC_LANG" ("ID") ENABLE;
  ALTER TABLE "SPC_DEFINITION_LANG" ADD CONSTRAINT "SPC_DEFINITION_LANG_FK2" FOREIGN KEY ("SPC_DEFINITION_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE;
--------------------------------------------------------
--$  DDL END Table SPC_DEFINITION_LANG
--------------------------------------------------------
--------------------------------------------------------
--$  DDL for Table SPC_DATA
--------------------------------------------------------

  CREATE TABLE "SPC_DATA" ("ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE 
                          , "SPC_ID" NUMBER
                          , "REF_TYPE_ID" NUMBER --& NEW
                          , "REF_ID" NUMBER --& NEW
                          , "VALUE" VARCHAR2(4000) COLLATE "USING_NLS_COMP"
                          , "CREATED" DATE
                          , "CREATED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                          , "MODIFIED" DATE
                          , "MODIFIED_BY" VARCHAR2(60) COLLATE "USING_NLS_COMP"
                          )  DEFAULT COLLATION "USING_NLS_COMP";

   COMMENT ON COLUMN "SPC_DATA"."SPC_ID" IS 'Reference the ID of the definition for the specifity the record is being created';
   COMMENT ON COLUMN "SPC_DATA"."REF_TYPE_ID" IS 'References the type of object id the specificity is being stored';
   COMMENT ON COLUMN "SPC_DATA"."REF_ID" IS 'References the id of the object the specoficity is being stored';
   COMMENT ON COLUMN "SPC_DATA"."VALUE" IS 'Value to be stored for the specificity';
   COMMENT ON COLUMN "SPC_DATA"."CREATED" IS 'Allows to identify the date the record was created';
   COMMENT ON COLUMN "SPC_DATA"."CREATED_BY" IS 'Allows to identify the user who created the record';
   COMMENT ON COLUMN "SPC_DATA"."MODIFIED" IS 'Allows identify the date the record was modified';
   COMMENT ON COLUMN "SPC_DATA"."MODIFIED_BY" IS 'allows to identify the user who modified the record';
--------------------------------------------------------
--  DDL for Index ID_SPC_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ID_SPC_DATA_PK" ON "SPC_DATA" ("ID");
--------------------------------------------------------
--  DDL for Index SPC_DATA_INDEX1
--------------------------------------------------------

  CREATE INDEX "SPC_DATA_INDEX1" ON "SPC_DATA" ("REF_ID");
--------------------------------------------------------
--  DDL for Trigger SPC_DATA_BIU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SPC_DATA_BIU" 
    before insert or update  
    on SPC_DATA 
    for each row
begin
    if inserting and :new.created is null then
        :new.created    := sysdate; 
        :new.created_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
    end if; 
    :new.modified    := sysdate; 
    :new.modified_by := nvl(sys_context('APEX$SESSION','APP_USER'),user); 
end SPC_DATA_BIU;
/
ALTER TRIGGER "SPC_DATA_BIU" ENABLE;
--------------------------------------------------------
--  Constraints for Table SPC_DATA
--------------------------------------------------------
  
  --ALTER TABLE "SPC_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("SPC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("MODIFIED" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" MODIFY ("MODIFIED_BY" NOT NULL ENABLE);
  ALTER TABLE "SPC_DATA" ADD CONSTRAINT "ID_SPC_DATA_PK" PRIMARY KEY ("ID") USING INDEX "ID_SPC_DATA_PK"  ENABLE;
  --** WILL BE REMOVED **--
  --ALTER TABLE "SPC_DATA" MODIFY ("REF_ID" NOT NULL ENABLE);
  --ALTER TABLE "SPC_DATA" MODIFY ("CONTRAT_ID" NOT NULL ENABLE)
  --ALTER TABLE "SPC_DATA" MODIFY ("UNITE_AFF_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table SPC_DATA
--------------------------------------------------------

  ALTER TABLE "SPC_DATA" ADD CONSTRAINT "SPC_DATA_FK1" FOREIGN KEY ("SPC_ID") REFERENCES "SPC_DEFINITION" ("ID") ENABLE
--------------------------------------------------------
--$  DDL END Table SPC_DATA
--------------------------------------------------------