
DROP TABLE "SPC_DATA";
DROP TABLE "SPC_DEFINITION_LANG";
DROP TABLE "SPC_DEFINITION";
DROP TABLE "SPC_GROUP_DEFINITION";
DROP TABLE "SPC_LOV_LANG";
DROP TABLE "SPC_LOV";
DROP TABLE "SPC_LANG";
DROP TABLE "SPC_VAL_COUNTER";
DROP TABLE "SPC_FORMAT";
